name: build

on:
  push:
    branches:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Pack
      if: github.ref == 'refs/heads/deploy'
      run: dotnet pack -c Release --no-build --include-source
    - name: Publish the package to nuget.org
      if: github.ref == 'refs/heads/deploy'
      run: dotnet nuget push */bin/Release/*.nupkg -k "${{ secrets.GITHUB_TOKEN }}" -s https://nuget.pkg.github.com/olsh/index.json --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}